-- ============================================================================
-- !!! ATENCIÓN — NO EJECUTAR EN LA BASE ACTUAL !!!
-- Este script es una migración DESTRUCTIVA: hace DROP TABLE y RE-CREA todo el
-- esquema desde cero. BORRA TODOS LOS DATOS (transportes, chat, usuarios, etc.).
--
-- Estado verificado (16:00, proyecto gklcxnlseghdqylvnkdb): el esquema YA ESTÁ
-- COMPLETO en la base (tablas, columnas, políticas RLS y datos). NO hay nada que
-- crear. Este archivo solo tiene utilidad para inicializar un proyecto NUEVO y
-- VACÍO. Ejecutarlo sobre la base actual = pérdida total de datos.
-- ============================================================================

-- =============================================
-- CCL-FLOW: MIGRACIÓN COMPLETA (v9)
-- Recrea el esquema unificado con:
--   - transportes (una fila por LLAVE) con dos estados separados:
--       estado_despacho  (DESPACHOS): ALISTADO, DESPACHADO, PTE ALISTAR
--                       (se elige al crear la llave)
--       estado_porteria  (PORTERÍA):  Pendiente, LLEGO A PORTERIA,
--                       INGRESO A MUELLE, CARGANDO, FINALIZO CARGUE,
--                       SALIO DE PORTERIA (columna ESTADO del modal
--                       principal de transportes, a la derecha de MUELLE)
--     y control de tiempos completo: transportadora, hora cita (slot),
--     llegada portería, ingreso portería, muelle asignado, inicio/fin
--     cargue y salida portería.
--     (v7: eliminada cita_entrega; hora_llamado_muelle renombrada a
--      hora_llegada_porteria)
--     (v5: eliminadas conductor, num_ordenes_ruta, peso_kg, cajas_originales,
--      cajas, orden_carga y conductor_telefono)
--   - clientes (CODIGO SHIP-TO + DENOMINACION) y ciudades (todas las de
--     Colombia, DIVIPOLA) para las listas desplegables del formulario
--   - chat_messages
--   - roles (ADMIN, DESPACHADOR, PORTERO, PLANEADOR, SUPERVISOR)
--   - users (nombre, cedula, clave, tipo_usuario)
--   - historial_movimientos (historial por usuario) con RLS permisivo
-- Ejecutar en el editor SQL de Supabase (Dashboard > SQL).
-- =============================================

BEGIN;

-- 1) Limpieza (CASCADE elimina dependencias/FKs)
DROP TABLE IF EXISTS historial_movimientos CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS facturacion CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS ciudades CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS transportes CASCADE;

-- 2) TRANSPORTES (tabla única de operación)
CREATE TABLE transportes (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  llave                 VARCHAR(20) NOT NULL UNIQUE,
  fecha_hora            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  placa                 VARCHAR(20) NOT NULL,
  numero_pedido         VARCHAR(30),
  vehiculo_tipo         VARCHAR(20) NOT NULL DEFAULT 'SENCILLO'
                        CHECK (vehiculo_tipo IN ('SENCILLO', 'TURBO', 'MINIMULA', 'LUV')),
  denominacion_cliente  VARCHAR(200) NOT NULL DEFAULT 'CLIENTE REGIONAL',
  destino               VARCHAR(200) NOT NULL DEFAULT 'NEIVA',
  cita_cargue           VARCHAR(50),
  transportadora        VARCHAR(200) NOT NULL DEFAULT '',
  estado_transporte     VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
                        CHECK (estado_transporte IN ('DESPACHADO', 'ALISTADO', 'PENDIENTE')),
  estado_despacho       VARCHAR(20) NOT NULL DEFAULT 'PTE ALISTAR'
                        CHECK (estado_despacho IN ('ALISTADO', 'DESPACHADO', 'PTE ALISTAR')),
  estado_porteria       VARCHAR(20) NOT NULL DEFAULT 'Pendiente'
                        CHECK (estado_porteria IN ('Pendiente', 'LLEGO A PORTERIA', 'INGRESO A MUELLE', 'CARGANDO', 'FINALIZO CARGUE', 'SALIO DE PORTERIA')),
  muelle_asignado       VARCHAR(50),
  hora_llegada_porteria VARCHAR(10) DEFAULT '--:--',  -- H. LLEGADA PORTERÍA
  hora_ingreso          VARCHAR(10) DEFAULT '--:--',  -- H. INGRESO PORTERÍA
  hora_inicio_cargue    VARCHAR(10) DEFAULT '--:--',  -- H. INICIO CARGUE
  hora_fin_cargue       VARCHAR(10) DEFAULT '--:--',  -- H. FIN CARGUE
  hora_salida           VARCHAR(10) DEFAULT '--:--',  -- H. SALIDA PORTERÍA
  observaciones         TEXT,
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_transportes_llave ON transportes(llave);
CREATE INDEX idx_transportes_placa ON transportes(placa);
CREATE INDEX idx_transportes_destino ON transportes(destino);
CREATE INDEX idx_transportes_estado_despacho ON transportes(estado_despacho);
CREATE INDEX idx_transportes_estado_porteria ON transportes(estado_porteria);
CREATE INDEX idx_transportes_estado_transporte ON transportes(estado_transporte);
CREATE INDEX idx_transportes_fecha_hora ON transportes(fecha_hora);

-- 3) CATÁLOGOS (clientes y ciudades) para las listas desplegables
CREATE TABLE clientes (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  codigo_ship_to    NUMERIC(10,0) NOT NULL UNIQUE,
  denominacion      VARCHAR(200) NOT NULL,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE ciudades (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ciudad            VARCHAR(100) NOT NULL UNIQUE,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_clientes_denominacion ON clientes(denominacion);
CREATE INDEX idx_ciudades_ciudad ON ciudades(ciudad);

INSERT INTO clientes (codigo_ship_to, denominacion) VALUES
  (1001, 'CEDI NEIVA'),
  (1002, 'EXITO CALI'),
  (1003, 'SERVITENDAS'),
  (1004, 'ALMACENES CARTAGENA'),
  (1005, 'SUPERINTER BOGOTA'),
  (1006, 'OLIMPICA'),
  (1007, 'HOME CENTER'),
  (1008, 'FALABELLA');

-- SEED CIUDADES (todas las ciudades de Colombia - DIVIPOLA)
INSERT INTO ciudades (ciudad) VALUES
  ('Abejorral'),
  ('Ábrego'),
  ('Abriaquí'),
  ('Acacías'),
  ('Acandí'),
  ('Acevedo'),
  ('Achí'),
  ('Agrado'),
  ('Agua de Dios'),
  ('Aguachica'),
  ('Aguada'),
  ('Aguadas'),
  ('Aguazul'),
  ('Agustín Codazzi'),
  ('Aipe'),
  ('Albán'),
  ('Albania'),
  ('Alcalá'),
  ('Aldana'),
  ('Alejandría'),
  ('Algarrobo'),
  ('Algeciras'),
  ('Almaguer'),
  ('Almeida'),
  ('Alpujarra'),
  ('Altamira'),
  ('Alto Baudó'),
  ('Altos del Rosario'),
  ('Alvarado'),
  ('Amagá'),
  ('Amalfi'),
  ('Ambalema'),
  ('Anapoima'),
  ('Ancuyá'),
  ('Andalucía'),
  ('Andes'),
  ('Angelópolis'),
  ('Angostura'),
  ('Anolaima'),
  ('Anorí'),
  ('Anserma'),
  ('Ansermanuevo'),
  ('Anzá'),
  ('Anzoátegui'),
  ('Apartadó'),
  ('Apía'),
  ('Apulo'),
  ('Aquitania'),
  ('Aracataca'),
  ('Aranzazu'),
  ('Aratoca'),
  ('Arauca'),
  ('Arauquita'),
  ('Arbeláez'),
  ('Arboleda'),
  ('Arboledas'),
  ('Arboletes'),
  ('Arcabuco'),
  ('Arenal'),
  ('Argelia'),
  ('Ariguaní'),
  ('Arjona'),
  ('Armenia'),
  ('Armero'),
  ('Arroyohondo'),
  ('Astrea'),
  ('Ataco'),
  ('Ayapel'),
  ('Bagadó'),
  ('Bahía Solano'),
  ('Bajo Baudó'),
  ('Balboa'),
  ('Baranoa'),
  ('Baraya'),
  ('Barbacoas'),
  ('Barbosa'),
  ('Barichara'),
  ('Barranca de Upía'),
  ('Barrancabermeja'),
  ('Barrancas'),
  ('Barranco de Loba'),
  ('Barranquilla'),
  ('Becerril'),
  ('Belalcázar'),
  ('Belén'),
  ('Belén de los Andaquíes'),
  ('Belén de Umbría'),
  ('Bello'),
  ('Belmira'),
  ('Beltrán'),
  ('Berbeo'),
  ('Betania'),
  ('Betéitiva'),
  ('Betulia'),
  ('Bituima'),
  ('Boavita'),
  ('Bochalema'),
  ('Bogotá'),
  ('Bojacá'),
  ('Bojayá'),
  ('Bolívar'),
  ('Bosconia'),
  ('Boyacá'),
  ('Brazuelo de Papayal'),
  ('Briceño'),
  ('Bucaramanga'),
  ('Bucarasica'),
  ('Buenaventura'),
  ('Buenavista'),
  ('Buenos Aires'),
  ('Buesaco'),
  ('Buga'),
  ('Bugalagrande'),
  ('Buriticá'),
  ('Busbanzá'),
  ('Cabrera'),
  ('Cabuyaro'),
  ('Cáceres'),
  ('Cachipay'),
  ('Cáchira'),
  ('Cácota'),
  ('Caicedo'),
  ('Caicedonia'),
  ('Caimito'),
  ('Cajamarca'),
  ('Cajibío'),
  ('Cajicá'),
  ('Calamar'),
  ('Calarcá'),
  ('Caldas'),
  ('Caldono'),
  ('Cali'),
  ('California'),
  ('Calima'),
  ('Caloto'),
  ('Campamento'),
  ('Campo de la Cruz'),
  ('Campoalegre'),
  ('Campohermoso'),
  ('Canalete'),
  ('Candelaria'),
  ('Cantagallo'),
  ('Cantón de San Pablo'),
  ('Cañasgordas'),
  ('Caparrapí'),
  ('Capitanejo'),
  ('Cáqueza'),
  ('Caracolí'),
  ('Caramanta'),
  ('Carcasí'),
  ('Carepa'),
  ('Carmen de Apicalá'),
  ('Carmen de Carupa'),
  ('Carolina del Príncipe'),
  ('Cartagena de Indias'),
  ('Cartagena del Chairá'),
  ('Cartago'),
  ('Carurú'),
  ('Casabianca'),
  ('Castilla la Nueva'),
  ('Caucasia'),
  ('Cepitá'),
  ('Cereté'),
  ('Cerinza'),
  ('Cerrito'),
  ('Cerro de San Antonio'),
  ('Cértegui'),
  ('Chachagüí'),
  ('Chaguaní'),
  ('Chalán'),
  ('Chámeza'),
  ('Chaparral'),
  ('Charalá'),
  ('Charta'),
  ('Chía'),
  ('Chibolo'),
  ('Chigorodó'),
  ('Chima'),
  ('Chimá'),
  ('Chimichagua'),
  ('Chinácota'),
  ('Chinavita'),
  ('Chinchiná'),
  ('Chinú'),
  ('Chipaque'),
  ('Chipatá'),
  ('Chiquinquirá'),
  ('Chíquiza'),
  ('Chiriguaná'),
  ('Chiscas'),
  ('Chita'),
  ('Chitagá'),
  ('Chitaraque'),
  ('Chivatá'),
  ('Chivor'),
  ('Choachí'),
  ('Chocontá'),
  ('Cicuco'),
  ('Ciénaga'),
  ('Ciénaga de Oro'),
  ('Ciénega'),
  ('Cimitarra'),
  ('Circasia'),
  ('Cisneros'),
  ('Ciudad Bolívar'),
  ('Clemencia'),
  ('Cocorná'),
  ('Coello'),
  ('Cogua'),
  ('Colombia'),
  ('Colón'),
  ('Colosó'),
  ('Cómbita'),
  ('Concepción'),
  ('Concordia'),
  ('Condoto'),
  ('Confines'),
  ('Consacá'),
  ('Contadero'),
  ('Contratación'),
  ('Convención'),
  ('Copacabana'),
  ('Coper'),
  ('Córdoba'),
  ('Corinto'),
  ('Coromoro'),
  ('Corozal'),
  ('Corrales'),
  ('Cota'),
  ('Cotorra'),
  ('Covarachía'),
  ('Coveñas'),
  ('Coyaima'),
  ('Cravo Norte'),
  ('Cuaspud'),
  ('Cubará'),
  ('Cubarral'),
  ('Cucaita'),
  ('Cucunubá'),
  ('Cúcuta'),
  ('Cucutilla'),
  ('Cuítiva'),
  ('Cumaral'),
  ('Cumaribo'),
  ('Cumbal'),
  ('Cumbitara'),
  ('Cunday'),
  ('Curillo'),
  ('Curití'),
  ('Curumaní'),
  ('Dabeiba'),
  ('Dagua'),
  ('Dibulla'),
  ('Distracción'),
  ('Dolores'),
  ('Donmatías'),
  ('Dosquebradas'),
  ('Duitama'),
  ('Duranía'),
  ('Ebéjico'),
  ('El Águila'),
  ('El Atrato'),
  ('El Bagre'),
  ('El Banco'),
  ('El Cairo'),
  ('El Calvario'),
  ('El Carmen'),
  ('El Carmen de Atrato'),
  ('El Carmen de Bolívar'),
  ('El Carmen de Chucurí'),
  ('El Carmen de Viboral'),
  ('El Carmen del Darién'),
  ('El Castillo'),
  ('El Cerrito'),
  ('El Charco'),
  ('El Cocuy'),
  ('El Colegio'),
  ('El Copey'),
  ('El Doncello'),
  ('El Dorado'),
  ('El Dovio'),
  ('El Espinal'),
  ('El Espino'),
  ('El Guacamayo'),
  ('El Guamo'),
  ('El Molino'),
  ('El Paso'),
  ('El Paujil'),
  ('El Peñol'),
  ('El Peñón'),
  ('El Piñón'),
  ('El Pital'),
  ('El Playón'),
  ('El Retén'),
  ('El Retiro'),
  ('El Retorno'),
  ('El Roble'),
  ('El Rosal'),
  ('El Rosario'),
  ('El Santuario'),
  ('El Socorro'),
  ('El Tablón'),
  ('El Tambo'),
  ('El Tarra'),
  ('El Zulia'),
  ('Elías'),
  ('Encino'),
  ('Enciso'),
  ('Entrerríos'),
  ('Envigado'),
  ('Facatativá'),
  ('Falán'),
  ('Filadelfia'),
  ('Filandia'),
  ('Firavitoba'),
  ('Flandes'),
  ('Florencia'),
  ('Floresta'),
  ('Florián'),
  ('Florida'),
  ('Floridablanca'),
  ('Fómeque'),
  ('Fonseca'),
  ('Fortul'),
  ('Fosca'),
  ('Francisco Pizarro'),
  ('Fredonia'),
  ('Fresno'),
  ('Frontino'),
  ('Fuente de Oro'),
  ('Fundación'),
  ('Funes'),
  ('Funza'),
  ('Fúquene'),
  ('Fusagasugá'),
  ('Gachalá'),
  ('Gachancipá'),
  ('Gachantivá'),
  ('Gachetá'),
  ('Galán'),
  ('Galapa'),
  ('Galeras'),
  ('Gama'),
  ('Gamarra'),
  ('Gámbita'),
  ('Gámeza'),
  ('Garagoa'),
  ('Garzón'),
  ('Génova'),
  ('Gigante'),
  ('Ginebra'),
  ('Giraldo'),
  ('Girardot'),
  ('Girardota'),
  ('Girón'),
  ('Gómez Plata'),
  ('González'),
  ('Gramalote'),
  ('Granada'),
  ('Guaca'),
  ('Guacamayas'),
  ('Guacarí'),
  ('Guachené'),
  ('Guachetá'),
  ('Guachucal'),
  ('Guadalupe'),
  ('Guaduas'),
  ('Guaitarilla'),
  ('Gualmatán'),
  ('Guamal'),
  ('Guamo'),
  ('Guapí'),
  ('Guapotá'),
  ('Guaranda'),
  ('Guarne'),
  ('Guasca'),
  ('Guatapé'),
  ('Guataquí'),
  ('Guatavita'),
  ('Guateque'),
  ('Guática'),
  ('Guavatá'),
  ('Guayabal de Síquima'),
  ('Guayabetal'),
  ('Guayatá'),
  ('Güepsa'),
  ('Güicán'),
  ('Gutiérrez'),
  ('Hacarí'),
  ('Hatillo de Loba'),
  ('Hato'),
  ('Hato Corozal'),
  ('Hatonuevo'),
  ('Heliconia'),
  ('Herrán'),
  ('Herveo'),
  ('Hispania'),
  ('Hobo'),
  ('Honda'),
  ('Ibagué'),
  ('Icononzo'),
  ('Iles'),
  ('Imués'),
  ('Inírida'),
  ('Inzá'),
  ('Ipiales'),
  ('Íquira'),
  ('Isnos'),
  ('Istmina'),
  ('Itagüí'),
  ('Ituango'),
  ('Iza'),
  ('Jambaló'),
  ('Jamundí'),
  ('Jardín'),
  ('Jenesano'),
  ('Jericó'),
  ('Jerusalén'),
  ('Jesús María'),
  ('Jordán'),
  ('Juan de Acosta'),
  ('Junín'),
  ('Juradó'),
  ('La Apartada'),
  ('La Argentina'),
  ('La Belleza'),
  ('La Calera'),
  ('La Capilla'),
  ('La Ceja'),
  ('La Celia'),
  ('La Cruz'),
  ('La Cumbre'),
  ('La Dorada'),
  ('La Esperanza'),
  ('La Estrella'),
  ('La Florida'),
  ('La Gloria (Cesar)'),
  ('La Jagua de Ibirico'),
  ('La Jagua del Pilar'),
  ('La Llanada'),
  ('La Macarena'),
  ('La Merced'),
  ('La Mesa'),
  ('La Montañita'),
  ('La Palma'),
  ('La Paz'),
  ('La Peña'),
  ('La Pintada'),
  ('La Plata'),
  ('La Playa de Belén'),
  ('La Primavera'),
  ('La Salina'),
  ('La Sierra'),
  ('La Tebaida'),
  ('La Tola'),
  ('La Unión'),
  ('La Uribe'),
  ('La Uvita'),
  ('La Vega'),
  ('La Victoria'),
  ('La Virginia'),
  ('Labateca'),
  ('Labranzagrande'),
  ('Landázuri'),
  ('Lebrija'),
  ('Leiva'),
  ('Lejanías'),
  ('Lenguazaque'),
  ('Lérida'),
  ('Leticia'),
  ('Líbano'),
  ('Liborina'),
  ('Linares'),
  ('Litoral de San Juan'),
  ('Lloró'),
  ('López de Micay'),
  ('Lorica'),
  ('Los Andes'),
  ('Los Córdobas'),
  ('Los Palmitos'),
  ('Los Patios'),
  ('Los Santos'),
  ('Lourdes'),
  ('Luruaco'),
  ('Macanal'),
  ('Macaravita'),
  ('Maceo'),
  ('Machetá'),
  ('Madrid'),
  ('Magangué'),
  ('Magüí Payán'),
  ('Mahates'),
  ('Maicao'),
  ('Majagual'),
  ('Málaga'),
  ('Malambo'),
  ('Mallama'),
  ('Manatí'),
  ('Manaure'),
  ('Manaure Balcón del Cesar'),
  ('Maní'),
  ('Manizales'),
  ('Manta'),
  ('Manzanares'),
  ('Mapiripán'),
  ('Margarita'),
  ('María la Baja'),
  ('Marinilla'),
  ('Maripí'),
  ('Mariquita'),
  ('Marmato'),
  ('Marquetalia'),
  ('Marsella'),
  ('Marulanda'),
  ('Matanza'),
  ('Medellín'),
  ('Medina'),
  ('Medio Atrato'),
  ('Medio Baudó'),
  ('Medio San Juan'),
  ('Melgar'),
  ('Mercaderes'),
  ('Mesetas'),
  ('Milán'),
  ('Miraflores'),
  ('Miranda'),
  ('Mistrató'),
  ('Mitú'),
  ('Mocoa'),
  ('Mogotes'),
  ('Molagavita'),
  ('Momil'),
  ('Mompós'),
  ('Mongua'),
  ('Monguí'),
  ('Moniquirá'),
  ('Montebello'),
  ('Montecristo'),
  ('Montelíbano'),
  ('Montenegro'),
  ('Montería'),
  ('Monterrey'),
  ('Moñitos'),
  ('Morales'),
  ('Morelia'),
  ('Morroa'),
  ('Mosquera'),
  ('Motavita'),
  ('Murillo'),
  ('Murindó'),
  ('Mutatá'),
  ('Mutiscua'),
  ('Muzo'),
  ('Nariño'),
  ('Nátaga'),
  ('Natagaima'),
  ('Nechí'),
  ('Necoclí'),
  ('Neira'),
  ('Neiva'),
  ('Nemocón'),
  ('Nilo'),
  ('Nimaima'),
  ('Nobsa'),
  ('Nocaima'),
  ('Norcasia'),
  ('Norosí'),
  ('Nóvita'),
  ('Nueva Granada'),
  ('Nuevo Colón'),
  ('Nunchía'),
  ('Nuquí'),
  ('Obando'),
  ('Ocamonte'),
  ('Ocaña'),
  ('Oiba'),
  ('Oicatá'),
  ('Olaya'),
  ('Olaya Herrera'),
  ('Onzaga'),
  ('Oporapa'),
  ('Orito'),
  ('Orocué'),
  ('Ortega'),
  ('Ospina'),
  ('Otanche'),
  ('Ovejas'),
  ('Pachavita'),
  ('Pacho'),
  ('Pácora'),
  ('Padilla'),
  ('Páez'),
  ('Paicol'),
  ('Pailitas'),
  ('Paime'),
  ('Paipa'),
  ('Pajarito'),
  ('Palermo'),
  ('Palestina'),
  ('Palmar'),
  ('Palmar de Varela'),
  ('Palmas del Socorro'),
  ('Palmira'),
  ('Palocabildo'),
  ('Pamplona'),
  ('Pamplonita'),
  ('Pandi'),
  ('Panqueba'),
  ('Páramo'),
  ('Paratebueno'),
  ('Pasca'),
  ('Pasto'),
  ('Patía'),
  ('Pauna'),
  ('Paya'),
  ('Paz de Ariporo'),
  ('Paz del Río'),
  ('Pedraza'),
  ('Pelaya'),
  ('Pensilvania'),
  ('Peque'),
  ('Pereira'),
  ('Pesca'),
  ('Piamonte'),
  ('Piedecuesta'),
  ('Piedras'),
  ('Piendamó'),
  ('Pijao'),
  ('Pijiño del Carmen'),
  ('Pinchote'),
  ('Pinillos'),
  ('Piojó'),
  ('Pisba'),
  ('Pitalito'),
  ('Pivijay'),
  ('Planadas'),
  ('Planeta Rica'),
  ('Plato'),
  ('Policarpa'),
  ('Polonuevo'),
  ('Ponedera'),
  ('Popayán'),
  ('Pore'),
  ('Potosí'),
  ('Pradera'),
  ('Prado'),
  ('Providencia'),
  ('Providencia y Santa Catalina Islas'),
  ('Pueblo Bello'),
  ('Pueblo Nuevo'),
  ('Pueblo Rico'),
  ('Pueblo Viejo'),
  ('Pueblorrico'),
  ('Puente Nacional'),
  ('Puerres'),
  ('Puerto Asís'),
  ('Puerto Berrío'),
  ('Puerto Boyacá'),
  ('Puerto Caicedo'),
  ('Puerto Carreño'),
  ('Puerto Colombia'),
  ('Puerto Concordia'),
  ('Puerto Escondido'),
  ('Puerto Gaitán'),
  ('Puerto Guzmán'),
  ('Puerto Leguízamo'),
  ('Puerto Libertador'),
  ('Puerto Lleras'),
  ('Puerto López'),
  ('Puerto Nare'),
  ('Puerto Nariño'),
  ('Puerto Parra'),
  ('Puerto Rico'),
  ('Puerto Rondón'),
  ('Puerto Salgar'),
  ('Puerto Santander'),
  ('Puerto Tejada'),
  ('Puerto Triunfo'),
  ('Puerto Wilches'),
  ('Pulí'),
  ('Pupiales'),
  ('Puracé'),
  ('Purificación'),
  ('Purísima'),
  ('Quebradanegra'),
  ('Quetame'),
  ('Quibdó'),
  ('Quimbaya'),
  ('Quinchía'),
  ('Quípama'),
  ('Quipile'),
  ('Ragonvalia'),
  ('Ramiriquí'),
  ('Ráquira'),
  ('Recetor'),
  ('Regidor'),
  ('Remedios'),
  ('Remolino'),
  ('Repelón'),
  ('Restrepo'),
  ('Ricaurte'),
  ('Río de Oro'),
  ('Río Iró'),
  ('Río Quito'),
  ('Río Viejo'),
  ('Rioblanco'),
  ('Riofrío'),
  ('Riohacha'),
  ('Rionegro'),
  ('Riosucio'),
  ('Risaralda'),
  ('Rivera'),
  ('Roberto Payán'),
  ('Roldanillo'),
  ('Roncesvalles'),
  ('Rondón'),
  ('Rosas'),
  ('Rovira'),
  ('Sabana de Torres'),
  ('Sabanagrande'),
  ('Sabanalarga'),
  ('Sabanas de San Ángel'),
  ('Sabaneta'),
  ('Saboyá'),
  ('Sácama'),
  ('Sáchica'),
  ('Sahagún'),
  ('Saladoblanco'),
  ('Salamina'),
  ('Salazar de Las Palmas'),
  ('Saldaña'),
  ('Salento'),
  ('Salgar'),
  ('Samacá'),
  ('Samaná'),
  ('Samaniego'),
  ('Sampués'),
  ('San Agustín'),
  ('San Alberto'),
  ('San Andrés'),
  ('San Andrés de Cuerquia'),
  ('San Andrés de Sotavento'),
  ('San Antero'),
  ('San Antonio'),
  ('San Antonio de Palmito'),
  ('San Antonio del Tequendama'),
  ('San Benito'),
  ('San Benito Abad'),
  ('San Bernardo'),
  ('San Bernardo del Viento'),
  ('San Calixto'),
  ('San Carlos'),
  ('San Carlos de Guaroa'),
  ('San Cayetano'),
  ('San Cristóbal'),
  ('San Diego'),
  ('San Eduardo'),
  ('San Estanislao'),
  ('San Fernando'),
  ('San Francisco'),
  ('San Gil'),
  ('San Jacinto'),
  ('San Jacinto del Cauca'),
  ('San Jerónimo'),
  ('San Joaquín'),
  ('San José'),
  ('San José de Albán'),
  ('San José de la Montaña'),
  ('San José de Miranda'),
  ('San José de Pare'),
  ('San José de Uré'),
  ('San José del Fragua'),
  ('San José del Guaviare'),
  ('San José del Palmar'),
  ('San Juan de Arama'),
  ('San Juan de Betulia'),
  ('San Juan de Rioseco'),
  ('San Juan de Urabá'),
  ('San Juan del Cesar'),
  ('San Juan Nepomuceno'),
  ('San Juanito'),
  ('San Lorenzo'),
  ('San Luis'),
  ('San Luis de Gaceno'),
  ('San Luis de Palenque'),
  ('San Marcos'),
  ('San Martín'),
  ('San Martín de Loba'),
  ('San Mateo'),
  ('San Miguel'),
  ('San Miguel de Sema'),
  ('San Onofre'),
  ('San Pablo'),
  ('San Pablo de Borbur'),
  ('San Pedro'),
  ('San Pedro de Cartago'),
  ('San Pedro de los Milagros'),
  ('San Pedro de Urabá'),
  ('San Pelayo'),
  ('San Rafael'),
  ('San Roque'),
  ('San Sebastián'),
  ('San Sebastián de Buenavista'),
  ('San Vicente'),
  ('San Vicente de Chucurí'),
  ('San Vicente del Caguán'),
  ('San Zenón'),
  ('Sandoná'),
  ('Santa Ana'),
  ('Santa Bárbara'),
  ('Santa Bárbara de Pinto'),
  ('Santa Catalina'),
  ('Santa Fe de Antioquia'),
  ('Santa Helena del Opón'),
  ('Santa Isabel'),
  ('Santa Lucía'),
  ('Santa María'),
  ('Santa Marta'),
  ('Santa Rosa'),
  ('Santa Rosa de Cabal'),
  ('Santa Rosa de Osos'),
  ('Santa Rosa de Viterbo'),
  ('Santa Rosa del Sur'),
  ('Santa Rosalía'),
  ('Santa Sofía'),
  ('Santacruz'),
  ('Santana'),
  ('Santander de Quilichao'),
  ('Santiago'),
  ('Santo Domingo'),
  ('Santo Domingo de Silos'),
  ('Santo Tomás'),
  ('Santuario'),
  ('Sapuyes'),
  ('Saravena'),
  ('Sardinata'),
  ('Sasaima'),
  ('Sativanorte'),
  ('Sativasur'),
  ('Segovia'),
  ('Sesquilé'),
  ('Sevilla'),
  ('Siachoque'),
  ('Sibaté'),
  ('Sibundoy'),
  ('Silvania'),
  ('Silvia'),
  ('Simacota'),
  ('Simijaca'),
  ('Simití'),
  ('Sincé'),
  ('Sincelejo'),
  ('Sipí'),
  ('Sitionuevo'),
  ('Soacha'),
  ('Soatá'),
  ('Socha'),
  ('Socotá'),
  ('Sogamoso'),
  ('Solano'),
  ('Soledad'),
  ('Solita'),
  ('Somondoco'),
  ('Sonsón'),
  ('Sopetrán'),
  ('Soplaviento'),
  ('Sopó'),
  ('Sora'),
  ('Soracá'),
  ('Sotaquirá'),
  ('Sotará'),
  ('Suaita'),
  ('Suán'),
  ('Suárez'),
  ('Suaza'),
  ('Subachoque'),
  ('Sucre'),
  ('Suesca'),
  ('Supatá'),
  ('Supía'),
  ('Suratá'),
  ('Susa'),
  ('Susacón'),
  ('Sutamarchán'),
  ('Sutatausa'),
  ('Sutatenza'),
  ('Tabio'),
  ('Tadó'),
  ('Talaigua Nuevo'),
  ('Tamalameque'),
  ('Támara'),
  ('Tame'),
  ('Támesis'),
  ('Taminango'),
  ('Tangua'),
  ('Taraira'),
  ('Tarazá'),
  ('Tarqui'),
  ('Tarso'),
  ('Tasco'),
  ('Tauramena'),
  ('Tausa'),
  ('Tello'),
  ('Tena'),
  ('Tenerife'),
  ('Tenjo'),
  ('Tenza'),
  ('Teorama'),
  ('Teruel'),
  ('Tesalia'),
  ('Tibacuy'),
  ('Tibaná'),
  ('Tibasosa'),
  ('Tibirita'),
  ('Tibú'),
  ('Tierralta'),
  ('Timaná'),
  ('Timbío'),
  ('Timbiquí'),
  ('Tinjacá'),
  ('Tipacoque'),
  ('Tiquisio'),
  ('Titiribí'),
  ('Toca'),
  ('Tocaima'),
  ('Tocancipá'),
  ('Togüí'),
  ('Toledo'),
  ('Tolú'),
  ('Tolú Viejo'),
  ('Tona'),
  ('Tópaga'),
  ('Topaipí'),
  ('Toribío'),
  ('Toro'),
  ('Tota'),
  ('Totoró'),
  ('Trinidad'),
  ('Trujillo'),
  ('Tubará'),
  ('Tuchín'),
  ('Tuluá'),
  ('Tumaco'),
  ('Tunja'),
  ('Tununguá'),
  ('Túquerres'),
  ('Turbaco'),
  ('Turbaná'),
  ('Turbo'),
  ('Turmequé'),
  ('Tuta'),
  ('Tutazá'),
  ('Ubalá'),
  ('Ubaque'),
  ('Ubaté'),
  ('Ulloa'),
  ('Úmbita'),
  ('Une'),
  ('Unguía'),
  ('Unión Panamericana'),
  ('Uramita'),
  ('Uribia'),
  ('Urrao'),
  ('Urumita'),
  ('Usiacurí'),
  ('Útica'),
  ('Valdivia'),
  ('Valencia'),
  ('Valle de San José'),
  ('Valle de San Juan'),
  ('Valle del Guamuez'),
  ('Valledupar'),
  ('Valparaíso'),
  ('Vegachí'),
  ('Vélez'),
  ('Venadillo'),
  ('Venecia'),
  ('Ventaquemada'),
  ('Vergara'),
  ('Versalles'),
  ('Vetas'),
  ('Vianí'),
  ('Victoria'),
  ('Vigía del Fuerte'),
  ('Vijes'),
  ('Villa Caro'),
  ('Villa de Leyva'),
  ('Villa del Rosario'),
  ('Villa Rica'),
  ('Villagarzón'),
  ('Villagómez'),
  ('Villahermosa'),
  ('Villamaría'),
  ('Villanueva'),
  ('Villapinzón'),
  ('Villarrica'),
  ('Villavicencio'),
  ('Villavieja'),
  ('Villeta'),
  ('Viotá'),
  ('Viracachá'),
  ('Vista Hermosa'),
  ('Viterbo'),
  ('Yacopí'),
  ('Yacuanquer'),
  ('Yaguará'),
  ('Yalí'),
  ('Yarumal'),
  ('Yolombó'),
  ('Yondó'),
  ('Yopal'),
  ('Yotoco'),
  ('Yumbo'),
  ('Zambrano'),
  ('Zapatoca'),
  ('Zapayán'),
  ('Zaragoza'),
  ('Zarzal'),
  ('Zetaquira'),
  ('Zipacón'),
  ('Zipaquirá'),
  ('Zona Bananera')
;

-- 3) CHAT MENSAJES
CREATE TABLE chat_messages (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_role       VARCHAR(50) NOT NULL,
  sender_name       VARCHAR(200) NOT NULL,
  sender_module     VARCHAR(20) NOT NULL
                    CHECK (sender_module IN ('Portería', 'Despachos', 'Planeación', 'General')),
  llave_relacionada VARCHAR(20) REFERENCES transportes(llave),
  muelle_sugerido   VARCHAR(50),
  content           TEXT NOT NULL,
  "timestamp"       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_read           BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- 4) ROLES (RBAC)
CREATE TABLE roles (
  id            VARCHAR(50) PRIMARY KEY,
  name          VARCHAR(100) NOT NULL UNIQUE,
  description   TEXT NOT NULL DEFAULT '',
  is_preset     BOOLEAN NOT NULL DEFAULT FALSE,
  permissions   JSONB NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO roles (id, name, description, is_preset, permissions) VALUES
  ('ROLE_ADMIN', 'ADMIN', 'Acceso total al sistema y gestión de roles, usuarios e historial.', true,
   '{"despachos":{"canAccess":true,"canEdit":true},"planeacion":{"canAccess":true,"canEdit":true},"porteria":{"canAccess":true,"canEdit":true},"personal":{"canAccess":true,"canEdit":true},"informes":{"canAccess":true,"canEdit":true},"admin_roles":{"canAccess":true,"canEdit":true},"usuarios":{"canAccess":true,"canEdit":true}}'),
  ('ROLE_DESPACHADOR', 'DESPACHADOR', 'Gestión de despachos y planeación.', true,
   '{"despachos":{"canAccess":true,"canEdit":true},"planeacion":{"canAccess":true,"canEdit":true},"porteria":{"canAccess":false,"canEdit":false},"personal":{"canAccess":false,"canEdit":false},"informes":{"canAccess":true,"canEdit":false},"admin_roles":{"canAccess":false,"canEdit":false},"usuarios":{"canAccess":false,"canEdit":false}}'),
  ('ROLE_PORTERO', 'PORTERO', 'Control de puerta, muelles y estados de portería.', true,
   '{"despachos":{"canAccess":true,"canEdit":false},"planeacion":{"canAccess":true,"canEdit":false},"porteria":{"canAccess":true,"canEdit":true},"personal":{"canAccess":false,"canEdit":false},"informes":{"canAccess":false,"canEdit":false},"admin_roles":{"canAccess":false,"canEdit":false},"usuarios":{"canAccess":false,"canEdit":false}}'),
  ('ROLE_PLANEADOR', 'PLANEADOR', 'Planeación de transporte y vista de despachos.', true,
   '{"despachos":{"canAccess":true,"canEdit":true},"planeacion":{"canAccess":true,"canEdit":true},"porteria":{"canAccess":false,"canEdit":false},"personal":{"canAccess":false,"canEdit":false},"informes":{"canAccess":true,"canEdit":false},"admin_roles":{"canAccess":false,"canEdit":false},"usuarios":{"canAccess":false,"canEdit":false}}'),
  ('ROLE_SUPERVISOR', 'SUPERVISOR', 'Observación global de la operación e informes.', true,
   '{"despachos":{"canAccess":true,"canEdit":false},"planeacion":{"canAccess":true,"canEdit":false},"porteria":{"canAccess":true,"canEdit":false},"personal":{"canAccess":true,"canEdit":true},"informes":{"canAccess":true,"canEdit":false},"admin_roles":{"canAccess":false,"canEdit":false},"usuarios":{"canAccess":false,"canEdit":false}}');

-- 5) USUARIOS (nombre, cedula, clave, tipo_usuario)
CREATE TABLE users (
  id            VARCHAR(50) PRIMARY KEY,
  nombre        VARCHAR(200) NOT NULL,
  cedula        VARCHAR(30) NOT NULL UNIQUE,
  clave         VARCHAR(100) NOT NULL,
  tipo_usuario  VARCHAR(20) NOT NULL
                CHECK (tipo_usuario IN ('admin', 'despachador', 'portero', 'planeador', 'supervisor')),
  role_id       VARCHAR(50) NOT NULL REFERENCES roles(id),
  role_name     VARCHAR(100) NOT NULL,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_users_role ON users(role_id);
CREATE INDEX idx_users_cedula ON users(cedula);

INSERT INTO users (id, nombre, cedula, clave, tipo_usuario, role_id, role_name) VALUES
  ('USER_ADMIN', 'ADMIN', '0000000000', 'admin', 'admin', 'ROLE_ADMIN', 'ADMIN'),
  ('USER_DESP', 'Juan Pérez', '1000000001', '1234', 'despachador', 'ROLE_DESPACHADOR', 'DESPACHADOR'),
  ('USER_PORTERO', 'Ramiro Torres', '1000000002', '1234', 'portero', 'ROLE_PORTERO', 'PORTERO'),
  ('USER_PLAN', 'Ana Gómez', '1000000003', '1234', 'planeador', 'ROLE_PLANEADOR', 'PLANEADOR'),
  ('USER_SUP', 'Luis Mora', '1000000004', '1234', 'supervisor', 'ROLE_SUPERVISOR', 'SUPERVISOR');

-- 6) HISTORIAL DE MOVIMIENTOS POR USUARIO
CREATE TABLE historial_movimientos (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario           VARCHAR(200) NOT NULL,
  tipo_usuario      VARCHAR(20) NOT NULL,
  cedula            VARCHAR(30),
  accion            VARCHAR(50) NOT NULL,
  modulo            VARCHAR(50) NOT NULL DEFAULT 'general',
  detalle           TEXT,
  llave_relacionada VARCHAR(20),
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_historial_usuario ON historial_movimientos(usuario);
CREATE INDEX idx_historial_accion ON historial_movimientos(accion);
CREATE INDEX idx_historial_created ON historial_movimientos(created_at);

COMMIT;

-- 7) ROW LEVEL SECURITY (acceso de la app)
-- Políticas permisivas: la app escribe/lee con la API anónima de Supabase.
ALTER TABLE transportes ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ciudades ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_movimientos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "app_full_access_transportes" ON transportes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "app_full_access_chat" ON chat_messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "app_full_access_clientes" ON clientes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "app_full_access_ciudades" ON ciudades FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "app_full_access_roles" ON roles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "app_full_access_users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "app_full_access_historial" ON historial_movimientos FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- NOTAS
-- =============================================
-- 1. Esta migración borra y recrea las tablas: no conserva datos previos.
--    Si necesitas conservar transportes existentes, haz un backup antes.
-- 2. ADMIN por defecto: cédula 0000000000 / clave admin.
